name:                ocaml-gi-gtk
version:             0.1.0.0
github:              "illbexyz/ocaml-gi-gtk"
license:             LGPL-2.1
author:              "Alberto Nicoletti"
maintainer:          "illbexyz@gmail.com"
copyright:           "Copyright (c) 2020 Alberto Nicoletti"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Short description of your package
category:            Development

description:         Please see the README on GitHub at <https://github.com/illbexyz/ocaml-gi-gtk#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-gi == 0.23.0
- text >= 1.0
- xml-conduit >= 1.3
- mtl >= 2.2
- containers
- filepath
- directory
- bytestring
- pretty-show
- haskell-gi-base >= 0.23.0 && <0.24
- regex-tdfa >= 1.2
- attoparsec >= 0.13

default-extensions:
- CPP
- LambdaCase
- OverloadedStrings
- RankNTypes

library:
  source-dirs: src

executables:
  ocaml-gi-gtk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ocaml-gi-gtk

tests:
  ocaml-gi-gtk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ocaml-gi-gtk
